export const ShouldError = [
    "Mars Rover",
    "Quantum Computer",
    "Sushi Roll",
    "Pineapple Pizza",
    "Origami Crane",
    "Starry Night Painting",
    "Giraffe",
    "Neon Sign",
    "Antique Clock",
    "Glacier",
    "Electric Guitar",
    "Hot Air Balloon",
    "Comic Book",
    "Fountain Pen",
    "Space Shuttle",
    "Yoga Mat",
    "Vintage Typewriter",
    "Chocolate Fondue",
    "Dinosaur Fossil",
    "Solar Panel",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z"
]